child/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.views import (
    LoginView, LogoutView
    )
from . import views
from django.conf.urls.static import static
urlpatterns=[
    path('',views.home,name="home"),
    path('login/',views.login1,name='login'),
    path('addmember/',views.addmember,name='addmember'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('logout/',views.logout1,name='logout'),
    path('register/',views.register,name='register'),
    path('allmembers/',views.allmembers,name='allmembers'),
    path('laststep/',views.laststep),
    path('congrats/',views.congrats),
    path('search/',views.searchmember,name='search'),
    path('searchresult/',views.searchresult),
    path('<int:memberid>',views.deletemember,name='deletemember'),
    path('allowuser/<int:id>',views.allowuser,name='allowuser'),
    path('allowuser',views.alloweduser,name='allowedusers'),
]

keshu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('child/',include('child.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



    
 

child/models.py
from django.db import models
from django.contrib.auth.models import User
from jsonfield import JSONField
class Member(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
	name=models.CharField(max_length=70)
	mobilenumber=models.IntegerField()
	gender=models.CharField(max_length=10)
	address=models.CharField(max_length=100)
	zip1=models.IntegerField()
	image=models.ImageField(upload_to='profile_image',blank=False)
	trained=models.BooleanField(default=False)
	missing = JSONField(default=dict)
	def __str__(self):
		return self.name
#class lost(models.Model):
#	user = models.ForeignKey(esehi,on_delete=models.CASCADE,null=True)
#	name=models.CharField(max_length=70)
#	mobilenumber=models.IntegerField()
#	gender=models.CharField(max_length=10,default='male')
#	address=models.CharField(max_length=100,default='Made')
#	zip1=models.IntegerField()
#	image=models.ImageField(upload_to='profile_image',blank=False)
#	def __str__(self):
#		return self.name

child/views.py
import os
import sqlite3
from django.template.loader import render_to_string
import cv2
from django.contrib.auth.models import User
import numpy as np
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from PIL import Image
from django.core.mail import send_mail
from django.template import Template,Context
from .models import Member
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
import requests
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags


def train():
  recognizer=cv2.face.LBPHFaceRecognizer_create();
  path='DataSet'
  def getImageWithID(path):
    imagePaths=[os.path.join(path,f) for f in os.listdir(path)]
    faces=[]
    IDs=[]
    for imagePath in imagePaths:
      faceImg=Image.open(imagePath).convert('L')
      facenp=np.array(faceImg,'uint8')
      ID=int(os.path.split(imagePath)[-1].split('.')[1])
      faces.append(facenp)
      IDs.append(ID)
      cv2.waitKey(10)
    return IDs,faces
  Ids,faces=getImageWithID(path)
  recognizer.train(faces,np.array(Ids))
  try:
    os.mkdir(settings.BASE_DIR+'/recognizer')
  except:
    None
  recognizer.write('recognizer/trainningData.yml')
  return None

def register(request):
  if request.method=='POST':
    username=request.POST['username']
    password=request.POST['password']
    cpassword=request.POST['password1']
    mobilenumber=request.POST['number']
    email=request.POST['email']
    if password==cpassword:
      user=User.objects.create_user(username,email,password)
      user.first_name=request.POST['firstname'] 
      user.last_name=request.POST['lastname']
      user.save()
      messages.success(request,'%s has been Registered Successfully'%user.username)
      return redirect('/child/login')
    else:
      messages.error(request,"Your password didn't match!")
      return redirect('/register')
  return render(request,'child/register.html')

def login1(request):
  if request.method=='POST':
    lusername=request.POST['username']
    lpassword=request.POST['password']
    user=authenticate(username=lusername,password=lpassword)
    if user is not None:
      login(request,user)
      messages.success(request,"%s has been logged Successfully"%user.username)
      return redirect('/child/dashboard')
    else:
      messages.error(request,'Invalid Username or Pssword')
      return redirect('/child/login')
  return render(request,'child/login.html')

@login_required
def logout1(request):
  logout(request)
  messages.success(request,'You have been logout Successfully')
  return redirect('/child')

@login_required
def congrats(request):
  faceDetect=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
  cam=cv2.VideoCapture(0)
  mem=list(Member.objects.all())[-1]
  id=mem.id
  sample=0
  try:
    os.mkdir(settings.BASE_DIR+"/DataSet")
  except:
    None
  while(True):
    ret,img=cam.read()
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=faceDetect.detectMultiScale(gray,1.3,5)
    for(x,y,w,h) in faces:
        sample=sample+1
        cv2.imwrite('DataSet/User.'+str(id)+"."+str(sample)+'.jpg',gray[y:y+h,x:x+w])
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
        cv2.waitKey(100)
    if(sample>20):
        break
  cam.release()
  cv2.destroyAllWindows()
  train()
  x=Member.objects.filter(id=id).update(trained=True)
  return render(request,'child/congrats.html')

@login_required
def laststep(request):
  return render(request,'child/laststep.html')

def home(request):
  return render(request,'child/index.html')

def success(request): 
    return HttpResponse('successfuly uploaded')

@login_required
def addmember(request):
  if request.method=="POST":
    name=request.POST['name']
    number=request.POST['number']
    gender=request.POST['gender']
    address=request.POST['address']
    code=request.POST['pincode']
    img=request.FILES['image']
    mem=Member()
    mem.user=request.user
    mem.name=name
    mem.mobilenumber=number
    mem.gender=gender
    mem.address=address
    mem.zip1=code
    mem.image=img
    mem.save()
    return redirect('/child/laststep')
  return render(request,'child/addmember.html')

@login_required
def dashboard(request):
  return render(request,'child/dashboard.html')

@login_required
def allmembers(request):
  members=Member.objects.filter(user=request.user)
  return render(request,'child/allmembers.html',{'members':members,'len':len(members)})

@login_required
def searchmember(request):
  return render(request,'child/searchmember.html')

def display_ip():
    """  Function To Print GeoIP Latitude & Longitude """
    ip_request = requests.get('https://get.geojs.io/v1/ip.json')
    my_ip = ip_request.json()['ip']
    geo_request = requests.get('https://get.geojs.io/v1/ip/geo/' +my_ip + '.json')
    geo_data = geo_request.json()
    a=[geo_data['region'],geo_data['latitude'],geo_data['longitude']]
    return a

@login_required
def searchresult(request):
  faceDetect=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
  def getans(Id):
    profile=None
    try:
      profile=Member.objects.get(id=Id)
    except:
      None
    return profile
  cam=cv2.VideoCapture(0)
  rec=cv2.face.LBPHFaceRecognizer_create();
  try:
    rec.read('recognizer\\trainningData.yml')
  except:
    return HttpResponse("There are no Members in our database to search with")
  id=0
  flag=0
  font=cv2.FONT_HERSHEY_COMPLEX_SMALL
  while(True):
    ret,img=cam.read()
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=faceDetect.detectMultiScale(gray,1.3,5)
    for(x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
        id,conf=rec.predict(gray[y:y+h,x:x+w])
        profile = getans(id)
        if profile!=None:
          cv2.destroyAllWindows()
          flag=1
          break
        #cv2.putText(img,str(id),(x,y+h), font, 4,(255,255,255),2,cv2.LINE_AA)
    cv2.imshow("Face",img);
    if(cv2.waitKey(1)==ord('q') or flag==1):
        break;
  cam.release()
  cv2.destroyAllWindows()
  current_site=get_current_site(request)
  to_email = profile.user.email
  Member.objects.filter(id=profile.id).update(missing = {'user':request.user.id,'Given':False})
  subject='Verify You Family Member Absence'
  r=display_ip()
  html_message = render_to_string('child/acc_active_email.html',context={'user':request.user,'profile':profile,'uid':urlsafe_base64_encode(force_bytes(id)),'url':"http://%s/child/allowuser/%s"%(current_site.domain,profile.id),'region':r[0],'long':r[1],'lat':r[2]})
  plain_message = strip_tags(html_message)
  x = send_mail(subject,plain_message,settings.EMAIL_HOST_USER,[to_email], html_message=html_message,fail_silently = True)
  if x==1:
    messages.success(request,f'We have sent the confirmation mail')
  return redirect('/child')
  #return render(request,'child/searchresult.html',{'profile':profile})'token':account_activation_token.make_token(request.user)


@login_required
def deletemember(request,memberid):
  s=Member.objects.get(id=memberid)
  t=s.name
  image=s.image
  s.delete()
  for sample in range(1,22):
    try:
      os.remove('DataSet/User.'+str(memberid)+"."+str(sample)+'.jpg')
    except:
      None
  os.remove('child/media/'+str(image))
  if len(Member.objects.filter(trained=True))!=0:
    train()
  else:
    try:
      os.remove('recognizer/trainningData.yml')
    except:
      None
  msg="%s has been removed successfully."%t;
  messages.success(request,'%s has been Removed Successfully'%t)
  return render(request,'child/allmembers.html')


def allowuser(request,id):
  x = Member.objects.get(id=id).missing
  x['Given'] = True
  print(x)
  Member.objects.filter(id=id).update(missing=x)
  return HttpResponse("We have give him access, we will inform him to connect you, we wish your member will be back to you safely as soon as possible.")

def alloweduser(request):
  profiles = Member.objects.all()
  accessed = []
  for pro in profiles:
    try:
      if pro.missing['user'] == request.user.id and pro.missing['Given']:
        accessed.append(pro)
    except:
      pass
  return render(request,'child/allowedusers.html',{'accessed':accessed})
#http://{{domain}}{% url 'activate' uidb64=uid token=token year=user.id %}

templates/child/acc_active_email.html
<!DOCTYPE html>
<html>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
<head>
    <style type="text/css">
        p{
            color: #5f6163;
        }
    </style>
</head>
<body style="background-color:#f2f2f2;padding-bottom: 5%;padding-top:5%;font-family: 'Roboto';">
    <div style="background-color: white;width: 48%;border-radius: 20px; padding: 4%;margin-left: auto;display:block;margin-right: auto;">
        <h4 style="text-align: center;font-size: 30px;">Verify Your Family Member Absence</h4>
        <h4 style="padding-top: 2%;margin-top: 0px;">Hi {{profile.user.first_name}}</h4>
        <p style="word-wrap: inherit;">{{user.first_name}} from {{region}}, wants to access your family member {{profile.name}} profile. Please confirm that your child absence, and if you want to give him access, Click on Allow {{user.first_name}}.</p>
        <br>
        <a href="{{url}}" style="text-decoration: none; display: block; background-color: #34b7dc; margin-left: auto;margin-right: auto;padding: 7px;border-radius: 3px;color: white;width: 250px;text-align: center;margin-bottom: 6%;">Allow {{user.first_name}}</a>
        <p>
        <p>If {{profile.name}} is having with you, no further action is required.</p>
        <p style="margin: 0%;padding: 0%;">Regards,</p>
        <p style="margin: 0%;padding: 0%;" >Milaap</p>
        <br>
        <div style="background-color: gray;min-height:1px;margin-bottom: 1%;margin-top: 3%;"></div>
            <p>If you're having trouble clicking the "Allow {{user.name}}" button, copy and paste the given URL below into your browser<br><a href="{{url}}">{{url}}</a></p>
    </div>
</body>
</html>

templates/child/addmember.html
{%extends 'child/basic.html'%}


{%block style%}
.col-md-3{
	display: inline-block;
	margin-left:-4px;
	margin-top:50px;

} 
.namak{
  text-align:center:
}



{%endblock%}

{%block body%}



<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Milaap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
        </div>
        <a class="btn btn-outline-success my-2 my-sm-0 mr-3" href="{% url 'dashboard' %}">Dashboard</a>
        <a class="btn btn-outline-success my-2 my-sm-0 mr-3" href="{% url 'logout' %}">Logout</a>
       
</nav>
         <div class="container">
        <form method="POST" action="{% url 'addmember' %}" enctype="multipart/form-data">{%csrf_token %}
  <div class="form-group">
    <label>Name</label>
    <input type="text" class="form-control" name='name'>
  </div>
  <div class="form-group">
    <label>Mobile Number</label>
    <input type="number" class="form-control" name='number'>
  </div>
  <div class="form-group">
    <label >Gender</label>
    <select class='form-conrol' name="gender">
    <option class='form-conrol' value="Male">Male</option>
    <option class='form-conrol' value="Female">Female</option>
</select>
  </div>
  <div class="form-group">
    <label>Address</label>
    <input type="text" class="form-control" name="address">
  </div>
  <div class="form-group">
    <label>Pin Code</label>
    <input type="number" class="form-control" name="pincode">
  </div>
  <div class="form-group">
    <label>Image</label>
    <input type="file" accept="image/*" class="form-control" name="image">
  </div>
  <button type="submit" class="btn btn-primary">Add Member</button>
</form>
      </div>
{%endblock%}

templates/child/allmembers.html
{%extends 'child/basic.html'%}

{%block style%}
.col-md-3{
  display: inline-block;
  margin-left:-4px;
  margin-top:50px;

} 
.namak{
  text-align:center:
}



{%endblock%}

{%block body%}


  
  
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/child">Milaap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/child/">Home <span class="sr-only">(current)</span></a>
      </li>
        </ul>
        </div>
        <a class="btn btn-outline-success my-2 my-sm-0 mr-3" href="{% url 'dashboard' %}">Dashboard</a>
        <a class="btn btn-outline-success my-2 my-sm-0 mr-3" href="{% url 'logout' %}">Logout</a>
       
</nav>
<div class="container" style="padding-top: 3%;">
{% if messages %}
{% for message in messages %}
<div class='alert alert-{{ message.tags }}'>
  {{ message }}
</div>
{% endfor %}
<a href="/child/dashboard">Go Back To Dashboard</a> 
  {% endif %}
{% if len is 0 %}
  <h1 style="text-align: center;">You have not added any member yet.</h1>
{% endif %}
{% for esehi in user.member_set.all %}
      <div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="/media/{{esehi.image}}" style="margin: auto;" class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{esehi.id}} {{esehi.name}} </h5>
        <p class="card-text">
        {{esehi.gender}}
      </p>
        <p class="card-text"><small class="text-muted">{{esehi.address}}<br>{{esehi.mobilenumber}}</small></p>
      </div>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalLong" style="float: right;margin-top: -25%;margin-right: 10%;">
      Delete
      </button>
      <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Delete Member</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are You Sure Want to delete this member ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="{% url 'deletemember' esehi.id %}" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
    </div>
  </div>
</div>
{% endfor %}
</div>
<!-- Button trigger modal -->


<!-- Modal -->

{%endblock%}

templates/child/allowedusers.html
{%extends 'child/basic.html'%}

{%block style%}
.col-md-3{
  display: inline-block;
  margin-left:-4px;
  margin-top:50px;

} 
.namak{
  text-align:center:
}
{%endblock%}
{%block body%}
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/child">Milaap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/child/">Home <span class="sr-only">(current)</span></a>
      </li>
        </ul>
        </div>
        <a class="btn btn-outline-success my-2 my-sm-0 mr-3" href="{% url 'dashboard' %}">Dashboard</a>
        <a class="btn btn-outline-success my-2 my-sm-0 mr-3" href="{% url 'logout' %}">Logout</a>
       
</nav>
<div class="container" style="padding-top: 3%;">
{% for esehi in accessed %}
      <div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="/media/{{esehi.image}}" style="margin: auto;" class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{esehi.id}} {{esehi.name}} </h5>
        <p class="card-text">
        {{esehi.gender}}
      </p>
        <p class="card-text"><small class="text-muted">{{esehi.address}}<br>{{esehi.mobilenumber}}</small></p>
      </div>
    </div>
  </div>
</div>
{% endfor %}
</div>
{%endblock%}

templates/child/basic.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Bootstrap CSS
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


    -->
    
    <title>Milaap</title>
    <link rel="icon" href="{% static 'img/child/search 1.png' %}" type="image/png">
    <style type="text/css">
     
    {%block style%}

    {%endblock%}
</style>
  </head>
  <body>
{%block body%} {%endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  
  </body>
</html>

templates/child/congrats.html
{%extends 'child/basic.html'%}


{%block style%}
.col-md-3{
	display: inline-block;
	margin-left:-4px;
	margin-top:50px;

} 
.namak{
  text-align:center:
}



{%endblock%}

{%block body%}

<style>
  body{
    background-color: #040201;
    background-repeat: no-repeat;
    background-size: cover;
  }

  h1{
    color: white;
    padding-top: 15rem ;
  }


  
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/child">Milaap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    
        </div>
        <a class="btn btn-outline-success my-2 my-sm-0 mr-3" href="{% url 'dashboard' %}">Dashboard</a>
        <a class="btn btn-outline-success my-2 my-sm-0 mr-3" href="{% url 'logout' %}">Logout</a>
       
</nav>
      <div class="container">
        <h1>Congratulations, You have Sucessfully Added a New Member</h1>

      </div>
{%endblock%}

templates/child/dashboard.html
{%extends 'child/basic.html'%}

{% load static %}
{%block style%}
.col-md-3{
  display: inline-block;
  margin-left:50px;
  margin-top:30px;

} 
.namak{
  text-align:center:
}



{%endblock%}

{%block body%}

<style>

  
  </style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/child">Milaap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
      </div>
        <a class="btn btn-outline-success my-2 my-sm-0 mr-3" href="{% url 'allowedusers'%}">Accessed</a>
        <a class="btn btn-outline-success my-2 my-sm-0 mr-3" href="{% url 'logout' %}">Logout</a>
       
</nav></br>
  {% if messages %}
{% for message in messages %}
<div class='alert alert-{{ message.tags }}'>
  {{ message }}
</div>
{% endfor %} 
  {% endif %}
<div style="margin-left: 10%;">
<div class="col-sm-3 col-xs-3 col-md-3 co">
<div class="card" style="width: 18rem; ">
  <img src="{% static 'img/child/titu.png' %}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Add Member</h5>
    <p class="card-text">In this section, You can add new Members</p>
    <a href="{% url 'addmember' %}" class="btn btn-primary">Go to Add</a>
  </div></div>
</div><div class="col-sm-3 col-xs-3 col-md-3">
<div class="card" style="width: 18rem;">
  <img src="{% static 'img/child/search 1.png' %}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Search Family</h5>
    <p class="card-text">
      Search Parents or any family member to unknown person.
    </p>
    <a href="{% url 'search' %}" class="btn btn-primary">Go to Search</a>
  </div></div>
</div>
<div class="col-sm-3 col-xs-3 col-md-3">
<div class="card" style="width: 18rem;">
  <img src="{% static 'img/child/members.png' %}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Show Members</h5>
    <p class="card-text">You can see all the member of you account which you had added.</p>
    <a href="{% url 'allmembers' %}" class="btn btn-primary">Go to Members</a>
  </div>
</div>
</div>
</div>
{%endblock%}

templates/child/laststep.html
{%extends 'child/basic.html'%}


{%block style%}
.col-md-3{
	display: inline-block;
	margin-left:-4px;
	margin-top:50px;

} 
.namak{
  text-align:center:
}



{%endblock%}

{%block body%}

<style>
  body{
    background-color: #040201;
    background-repeat: no-repeat;
    background-size: cover;
  }

  h3{
    color: white;

  }

  .container{
    padding-top: 15rem;
    padding-left: 22rem ;
  }
  
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Milaap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
        </div>
       
</nav>
      <div class="container">
<h3> Last Step For adding Member</h3><br>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a class="btn btn-outline-success" href="/child/congrats">Click Here for Trainning</a>  

      </div>
{%endblock%}

templates/child/login.html
{%extends 'child/basic.html'%}


{%block style%} 
.namak{
  text-align:center:
}



{%endblock%}

{%block body%}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/child">Milaap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
        </div>
      <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'register' %}">Registration</a>
  
</nav>
<div class="container">
  {% if messages %}
{% for message in messages %}
<div class='alert alert-{{ message.tags }}'>
  {{ message }}
</div>
{% endfor %} 
  {% endif %}
  <form method="POST" action="{% url 'login' %}">{% csrf_token %}
  <div class="form-group">
    <label>Username</label>
    <input type="text" class="form-control" name='username'>
  </div>
  <div class="form-group">
    <label>Password</label>
    <input type="password" class="form-control" name='password'>
  </div>
  <button type="submit" class="btn btn-primary">LogIn</button>
</form>
</div>
{%endblock%}